### ISSUE TITLE
Pokemons not in order in pokedex page

### ISSUE THREAD

**Issue by mfkaptan** [PokemonGoers/Catch-em-all#104]
Some pokemons are in the wrong place on the pokedex index page. Some of them are:
19 Ratata, 129 Magikarp, 132 Ditto

![image](https://cloud.githubusercontent.com/assets/3976573/19221138/7909946c-8e3d-11e6-83be-5b689dc3efeb.png)

**Comment by AlexanderLill** [comment]
This is because the pokemon are not sorted by the @PokemonGoers/pokedata team, meaning the call to `api/pokemon` returns the pokemon `1, 2, 3, 132, 4, ...` etc.

I think it would make the most sense if we sort them client-side - what do you guys think? @PokemonGoers/catch-em-all 

This looks like a valid solution:
http://stackoverflow.com/questions/32882013/angular-2-sort-and-filter

**Comment by WoH** [comment]
I have just briefly looked at stackoverflow, but a sorting pipe (orderById) is the way to go here.
Angular 2 doesn't ship with one, but the complexity is very low.

**Comment by swathi-ssunder** [comment]
This is now fixed and the API returns the Pokemons in ascending order of pokemon ids.
Someone could close this issue as I do not have access.

**Comment by WoH** [comment]
Guess that works aswell :smile:

**Comment by AlexanderLill** [comment]
@swathi-ssunder thanks :)
