### ISSUE TITLE
Welcome :)

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#15]
Hey everyone,

at first when I originally signed up for this seminar in the matching system I didn't get in. However, now that I'm in I'm a bit late to the party. I'm guessing that there was some kick-off meeting that I didn't attend. So, I have some questions:
- [x] How many members are we?
- [x] What's the deadline?
- [x] Do we have regular team meetings?
- [x] We need a fast way to communicate. ~~What's App, maybe?~~ Let's use gitter, see issue #14

Josef

**Comment by WoH** [comment]
@MajorBreakfast 
Hi and welcome, 
we are currently 8 members, 
our deadline and all the official details should be listed here:
https://rostlab.org/owiki/index.php/Javascript_technology_2016-2

We use gitter to communicate:
https://gitter.im/rostlabjs16projecte/Lobby

**Comment by WoH** [comment]
Also, you should've been added to the JST Group on by Guy on Google Group: 
https://groups.google.com/forum/#!forum/javascript-technology-2016-ws

Otherwise, request an invite please.

**Comment by MajorBreakfast** [comment]
@WoH 
- I just got the google group invite. There was a slight delay because my google account has a different email address. So, that's now alright.
- I think that we all should meet in person at the university from time to time
- What do we need to get done before presentation week? (Except the presenation itself of course)

**Comment by WoH** [comment]
We can set up meetings, there is some planning going on via gitter.
I will personally not press this in any way tough.

Our To-Do list is pretty much the Issue tracker, specifically #3 , #6 #7 #8 and #9 .
Basically a mobile-first JS application that integrates all the other Projects. You can find details about these here: https://rostlab.org/owiki/index.php/Javascript_technology_2016-2

I've done mockups to wrap my head around it here: #5

**Comment by WoH** [comment]
Deadline should be in 41 days if my calculations are correct.

**Comment by MajorBreakfast** [comment]
I'm wondering why the projects are supposed to start before presentation week. I don't really get what the talks are really for if everyone is already supposed to know everything about JavaScript development beforehand. The talks are supposed to introduce everyone to various topics and on the other hands we're supposed to choose a suitable framework in advance. I don't see how other team members that haven't worked on various projects before can chime in then.

**Comment by WoH** [comment]
I can't help you out with this, I guess this is just the way it is right now..
@juanmirocks @sacdallago are in charge, foward your concerns to them :smiling_imp:

**Comment by gyachdav** [comment]
@MajorBreakfast not really the place to discuss this on a GitHub issue but since we have it on here i'll answer anyways. 

The seminar used to be primarily about researching and presenting the topics and in addition building a small web app that is related to the assigned topic. Over the past two semesters we are trying to move to a new model in which the projects are becoming more important, however we are still required to have the presentations as this is still a seminar and not a practical. The idea is that students at all level will be able to contribute whether to the development effort or the academic side. 

Furthermore, we do not expect all students to have more than familiarity level with JavaScript and so sitting in through a week of presentations about fundamental aspects of the language  would be valuable. 

At any rate if you have further questions about the course you may send them directly to me.

**Comment by MajorBreakfast** [comment]
@gyachdav Ah I see. Thanks for the clarification!

I'm closing this issue now. #17 now deals with the team meeting.
