### ISSUE TITLE
Team Meeting

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#17]
Let's meet in person! Here's the doodle:

http://doodle.com/poll/iisgiiv97qsqykhi

Note that I've included tomorrow in the list. However, that's maybe a bit too soon. Let's just see how quick everyone is with filling in the doodle.

**Comment by MajorBreakfast** [comment]
Update: 5 of 8 people already responded. Looks like we're going to meet at 6pm on either Wed, Thu, or Fr!

**Comment by sacdallago** [comment]
@MajorBreakfast good initiative! But this is one of those things I would keep on google groups or gitter chat rather than github issues :) A rule of thumb: anything organizational or out-of-project-topic you better decide elsewhere

**Comment by MajorBreakfast** [comment]
@sacdallago Because gitter is a chat it's very easy to miss something like a link. Unless you're totally against it I'd rather track important things with a clear end date as issues as well. This issue will be closed in less than a week. (If you close it again, I won't reopen)

**Comment by sacdallago** [comment]
Hm... I rather have you use google groups then (if in gitter you loose track, which is understandable. It's also totally ok if you open a thread now! If one of us tutors will be free, we might join as well).
It's bad practice to mix organizational aspects with code in open-source communities :)
Don't get me wrong! I don't mean to be an asshole! But I rather have you do things the usual/right way  so that you are used to the practices when out in the wild :)
Also, I try to avoid having to deal with the "why didn't you tell them from the beginning?" stuff. I get plenty critiques all the time anyway :joy:

**Comment by MajorBreakfast** [comment]
@sacdallago Ah okay. So, I'll post it in Google groups.

**Comment by MajorBreakfast** [comment]
Here is the link to the google group post. I've created a channel for all imporant Project E announcements. 

https://groups.google.com/forum/#!topic/javascript-technology-2016-ws/qHMTX8Og9eo
