### ISSUE TITLE
Book room for team meeting

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/Catch-em-all#22]
- [x] Book room
- [x] Bring whiteboard markers
- [x] Bring HDMI cable and adapter to DisplayPort

**Comment by MajorBreakfast** [comment]
BTW the tutors don't want that we create organizational issues ;) Don't do it :P

**Comment by AlexanderLill** [comment]
I just had the following quote from Tatyana Goldberg in my mind when I booked the room:
»Do not hold back with reporting EVERYTHING that's happening around your project on GitHub. It takes some time, but soon reporting on GitHub will be as natural for you as brushing the teeth :)«

But okay, thanks for the clarification on that :)

**Comment by MajorBreakfast** [comment]
I agree. GitHub is great. Originally #17 was about the team meeting. In there Christian Dallago said that we should use GitHub solely for technical stuff. If it were up to me, I'd rather track teem meeting preparations as issues. I don't like Google Groups 'cause they're slow and clunky.

**Comment by MajorBreakfast** [comment]
I agree. GitHub is great. Originally #17 was about the team meeting. In there Christian Dallago said that we should use GitHub solely for technical stuff. I don't like Google Groups 'cause they're slow and clunky. Gitter is also bad because a chat is not permanent enough. Tracking organizational stuff on GitHub would feel nice. Nevertheless there is value in keeping things like meetings private... so Google Groups it is.

**Comment by sacdallago** [comment]
@AlexanderLill sorry about the mess up. @goldbergtatyana is totally right but I understand that the

> around your project

bit may confuse at times . I'll just expand:
- GitHub --> Code/project related issues
- Google Groups --> Organizational matters, announcments, JavaScript questions, personal/team problems

**Comment by AlexanderLill** [comment]
I see, thanks for the clarification :)
