### ISSUE TITLE
PokeData JavaScript API

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#23]
## This information is outdated and is currently due to refactoring.

Hey everyone,

this issue is about the client-side PokeData API that is shared between teams. After the discussion in this issue, the resulting API should both include what we, the app team, need and what you, the other teams, can provide. You, the other teams, have a lot to say about this. We're not going to dictate how the end result has to look. This issue is about finding the common ground on how things should look like. I will update this first post, so that the outlined API reflects what is discussed in the comments below. After the API stabilizes we're going to put the spec as a file into the repository.
## Architecture Overview

![architecture](https://cloud.githubusercontent.com/assets/340142/18185496/351e1f14-709e-11e6-84f9-86f266343adb.png)

@PokemonGoers/PokeData
~~It's necessary for you to build the PokeData JS API, a client-side library that the map teams and we, the app team, can use.~~
**Edit:** We, the app team, will build a client-side JavaScript PokeData API that talks to the JSON API provided by your server.

@PokemonGoers/pokemap-1
@PokemonGoers/pokemap-2
The map is an essential part of the UI. I think we will be able to connect everything nicely via some methods and events. The design of the map API (that relies on the data API) is tracked in #24.

@PokemonGoers/hashpokemongo
Your information will be used for the Pokemon predictions. That's between you and the data team. Let's track in a separate issue what you want us, the app team, to display additionally as information in the app with graphs and list of tweets and the like. Then, we can extend this API to include that information.

@PokemonGoers/predictpokemon-1
@PokemonGoers/predictpokemon-2
The architecture diagram currently shows the data team responsible for the server. However, the predictions consist of data produced by you. So, you and the data team need to cooperate closely, so that their server can serve it over the JSON API to the client-side PokeData JS API.
### Notation
- `async` means the method returns a promise ([MDN article about promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise))
- `get`, `set` designate an accessor property ([MDN article about getters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/get))
- `coordinates` are of the form `[latitude, longitude]`
- `range` is a `Number` in meters. It's a radius, but it's up to the data team which norm they want to use
### PokeData JS API
- class `PokeData`
  - `PokeData({ url })` constructor
  - `async getPokemonIds()` returns an array with pokemon ids as numbers.
  - `async getPokemon(pokemonId)` returns a `Pokemon` object: The pokemon data does not change, so it can be cached.
  - `async getPokemonSightings({ coordinates, range, ... })` returns array with `PokemonSighting` objects. It also loads the pokemon info.
  - `async getPokemonPredictions({ coordinates, range, ... })` returns array with `PokemonPrediction` objects. It also loads the pokemon info.
  - `async getPokeMobs({ coordinates, range })` returns array with `PokeMob` objects
  - `async searchCoordinates(searchTerm)` returns an array with `{ name, coordinates }` objects. This is needed for the location search box (low priority right now)
- class `Pokemon`
  - `pokemonID` (Number)
  - `name`
  - `description`
  - `image32URL`, `image512URL` URLs to 32x32, 512x512 .png files with transparency. Sizes might change in the future, so the images should ideally be generated from high res (>=1024px) images
  - Various other Pokemon info properties: `maxHP`, `maxCP`, `fleeRate`, `classification`, `gender`, `previousEvolutions`, `nextEvolutions`, `height`, `weight`, `specialAttacks`, `fastAttacks`, `weakness`, `resistance`, `types`
- class `PokePOI`: A point of interest that can be displayed on the map
  - `coordinates`
- class `PokemonSighting` extends `PokePOI`
  - `date` a JavaScript `Date` object
  - `pokemon` preloaded pokemon object, not async
- class `PokemonPrediction` extends `PokePOI`
  - `confidence`
  - `date` a JavaScript `Date` object
  - `pokemon` preloaded pokemon object, not async
- class `PokeMob` extends `PokePOI`
  - `date` a JavaScript `Date` object
## Links
- Current API by the data team http://pokedata.c4e3f8c7.svc.dockerapp.io:65014/doc
## Open questions
- What filter options should we have? (In addition to coordinates and range)
- What data properties are missing from `PokemonSighting`?
- What data properties are missing from `PokemonPrediction`?
- What data properties are missing from `PokeMob`? Is there a Pokemon involved? Tweets?
## Tasks
- Each team should appoint a least one **contact person** for coordination with us, the app team. Nevertheless it'd be of course best if all team members participated in the discussion!

I'm looking forward to everyone's thoughts! Let's begin coordinating!

**Comment by sacdallago** [comment]
I'm pretty short on time right now but there are several things here which are mixed up. Let me produce a good answer tomorrow morning (it's very much night where I am :D ).
Don't freak out, anyone. :)

**Comment by MatthiasBaur** [comment]
Would you mind switching Longitude/Latitude to Latitude/Longitude? I think it is the standard notation.

**Comment by MajorBreakfast** [comment]
@MatthiasBaur I changed it. And "latitude" is even spelled correctly now :)

**Comment by MajorBreakfast** [comment]
@jonas-he wrote in https://github.com/PokemonGoers/PokeData/issues/107#issuecomment-244118913:

> I think youve already seen our first version of the API as you already mentioned it in your other post. ou don't have to use a stub implementation, you simply have to call these URLs like [...] Why would you want to blow that up into a whole package?

A JS API has to exist in addition to the JSON API. Instead of making calls API calls to the JSON API from a multitude of places it is much more reasonable to make all calls from a single place, a dedicated client-side library. Furthermore having a JS API means that we get instances of classes instead of POJOs which can have convenience functions. And last but not least, the main reason, we get well defined objects that we can pass to and get from the map. Since the JS API has to be kept in sync with the JSON API, I thought that it would be best if you, the data team, build it. We can build it ourselves too though if you want to stay server-side only.

> Also in your architecture you got something slightly wrong: not only twitter but also the other data sources do contribute to the prediction.

Thx. I've added the arrow.

@sacdallago wrote:

> [...] but there are several things here which are mixed up [...]

Hehe. I expected as much :)

**Comment by jonas-he** [comment]
@MajorBreakfast I think we'll stay server-side :smile:

**Comment by MajorBreakfast** [comment]
> I think we'll stay server-side

@jonas-he I've updated the architecture to reflect that. Should be fine.

**Comment by AlexanderLill** [comment]
Hi everyone,

I have a question regarding the screen where we want to show the static information about a pokemon (also called the "wiki" in a few other places).

Is all the information that we want to show in that screen already included in the `pokemon` class, or do we need to talk about additional fields that we might need here or even another source of information? (@PokemonGoers/catch-em-all @jonas-he)

**Comment by sacdallago** [comment]
Phew, where to start :D

Well, thanks for the effort @MajorBreakfast it sure is nice to see such a complete overview :) I'm sorry that this comes a bit late but yesterday I couldn't attend to GitHub for some good reason.
I'm gonna try to be extremely schematic here:
1. The Data Team, aka @PokemonGoers/pokedata will produce a REST API incorporating everything data-related.
   -  Should other teams need any routes that are not implemented, they can ask (nicely) the folks of A to implement these via an Issue which will be discusses (sometimes other mentors, I or project members doom some routes to be unnecessary or irrelevant, so we will say "no").
   -  Should other teams need additional data, this also has to go through an issue and discussion, to see how relevant it is to the scope of project A
2. Other teams (except you) should package their tools into npm packages and it has to be seen where these make sense to be used. For the map team, it obviously makes sense that you use their package (probably wrapped with webpack or something similar), and import the "module" where it makes sense on the webpage. For the prediction team it might be that they join the package with project A, so that by querying a certain route (eg `https://someserver.com/predict/bulbasour?lat=x&lng=y&rad=10`) it will answer with data that conforms to the map team's standards and that can simply be shown on the map (er even better: the map teams already have an interface to display this information and you just have to initialize the map passing it the endpoint's location to get the data, aka `https://someserver.com`).This is the way it was done last semester, and I believe it's the thing that makes most sense.
3. There is a live-twitter listener, and this one is gonna be implemented in the map teams with the help of @PokemonGoers/hashpokemongo . This is quite new, so I can't tell how it was done in the past or how it will actually work, but **in my opinion** this will simply be part of what the map teams will deliver. Aka: if a user wants to see the live streaming of tweets and the formation of _pokeMobs_, he/she will be given a UI element on the website that allows for the streaming listener to start.

For your point on project A delivering a frontend API to their API in order to map the services to classes and functions: as you corrected it already, that's your job, not theirs. The are a variety of reasons why, among the most relevant to you/them: the workload needs to be evened out somehow, and project A is historically the heaviest project (even if we try to take away parts).

Now about the API calls:

> async getPokeMobs({ coordinates, range }) returns array with PokeMob objects

This is a subscription like thing. I already suggested @PokemonGoers/hashpokemongo to look into socket.io and stuff like that because this is not simply a call that closes, it's an open communication between server and client, and the Mobs are derived from the data that is fetched from twitter. So I would rather say  there will be something like `startStream({ coordinates, range })` and it will be part of the map projects, and when that is started the returned object will have listeners `.on('mob')` that will generate some event, **but** in the map itself this will already be represented (so the logic of dealing with mobs inside the map is encapsulated in the map projects).

This is relevant also to

> class PokeMob extends PokePOI

which will not have static attributes but rather event listeners.

Hope this makes sense.. I will start now going over what I missed yesterday :skull:

**Comment by MajorBreakfast** [comment]
@sacdallago 

About the data flow on the client:

The current approach assumes that the app team builds a filtering UI, fetches the data and gives it as `PokePOI` objects to the map. So, the map handles the user interaction, but displays only what it is told to display. It only talks to the map server for images and to no other data source. The alternative is that we, the app team, just build a filtering UI, hand the options to the map, the map talks to the poke data server and then we, the app team, get the relevant data from events by the map when something should open. Which approach did you have in mind when you planned the project? If I had to guess you had the latter approach in mind. This would mean of course that the API as I outline it here has no need to exist in that form. The map teams could simply open issues in your project for any filter UI they need.

About the streaming API:

If we make the `PokeMob`s a subscription based, it is logical to extend it to all `PokePOI`s. Sightings, predictions, mobs - they all appear over time. As for the tech: I'd say use websockets directly 'cause the support is there in every modern browser nowadays. IMO not much need for a wrapper.

**Comment by AlexanderLill** [comment]
Added field "description" to pokemon according to https://github.com/PokemonGoers/PokeData/issues/142

Will update this in a feature branch in a sec

**Comment by MajorBreakfast** [comment]
This has been implemented differently now. We, the app team, use an angular service. The map teams have their own implementations for talking to the JSON API.

**Comment by johartl** [comment]
Final draft

![Architecture](https://cloud.githubusercontent.com/assets/12528430/18781253/4cf0c184-8181-11e6-8a16-9a0313f5a119.png)

[architecture.pdf](https://github.com/PokemonGoers/Catch-em-all/files/491163/architecture.pdf)
