### ISSUE TITLE
Shell of MVC web app

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#3]
Decide on which JavaScript framework to use (Angular, React, Backbone) and create a shell of a Model-View-Controller website.

**Comment by sacdallago** [comment]
I **STRONGLY** suggest that you start looking into:
- https://meteor.com
- http://ionicframework.com
- Cordova / PhoneGap
- https://www.nativescript.org/

PokemonGo is played on mobile phones so the best idea would be have the web-app run natively on a mobile phone ;)

**Comment by johartl** [comment]
@sacdallago Thanks for your hints. From your personal experience, do you have any preference for one framework or the other? How do they differ and is there a framework you would recommend for this project?

**Comment by WoH** [comment]
@johartl If we use React, we can use React Native for mobiles.
Same goes for Angular 2 and Ionic 2 or Angular 1 and Ionic.
Nativescript is new to me, I'll check it out. I like A2 with Typescript so it looks interesting.

**Comment by sacdallago** [comment]
@johartl honestly I never yet used any :see_no_evil: 
I used meteor when it was still in alpha and beta up to 0.9 and it's an excellent framework! I heard from my ex-colleagues that it's also fairly easy to package the apps in iOS and android apps.

I'd personally go for ionic (2 + angular) because they seem the most exciting.

@WoH the only thing about A2 that doesn't convince me is TypeScript... Don't get me wrong, it is interesting, but this is a js seminar and I know that in the end you translate TS in JS but still... Mmmmhhh

**Comment by WoH** [comment]
@sacdallago Doesn't that exclude React aswell then since it uses JSX? Like I'm fine using whatever I just don't completely see the argument. Both are supersets of JS.

**Comment by sacdallago** [comment]
@WoH true. But we'd like to keep you superset or framework agnostic for as much as we can, though I obviously see the limitations in that concern (being that I myself suggested framework to start with ahah)
@gyachdav you have the final word

**Comment by gyachdav** [comment]
No problem with A2 in principal. Just keep in mind that other projects may want to contribute code to your repo and if they encounter Typescript that may discourage them from doing so (or they'll just ask you to develop features for them). So if I were you I'll try to stick to something more familiar. For instance m, the transition from JS to JSX is really straightforward.

**Comment by WoH** [comment]
Thanks for clarifying @sacdallago and @gyachdav . I can definitely see that.
Although I think we could use Typescript without type annotations or more "vanilla JS" style, we might just be better off using React and maybe lower the barrier for people that haven't used either one of these yet. You certainly need more initial understanding of the framework in the case of A2.

**Comment by johartl** [comment]
I suppose we can just use A2 with ES2015 syntax? I tried TypeScript myself once and encountered some difficulties with the type definition files of external libraries (they were either incomplete or incorrect). This can be really frustrating for inexperienced developers and just introduces some barriers to learning Angular (or any other framework).

**Comment by johartl** [comment]
@sacdallago @gyachdav I'm a bit confused. I initially thought that the expected outcome of the project is a web app that runs in the browser and is tailored towards mobile devices. But if I understand correctly, Ionic, ReactNative and PhoneGap are all frameworks to create an Android/iOS app. 
So, are there any restrictions or preferences on the platform ("native" app or web app)? And also, won't the choice of platform ultimately affect the other teams as well? For instance, I could imagine that the way of displaying a map differs depending on whether we are using Ionic or Meteor.

**Comment by sacdallago** [comment]
@johartl very good observation. Let me go into a few things here:

It depends on the framework you choose:
- With Meteor, you can develop the entire application as a native web-app and then just [add the ios/android SDKs](https://www.meteor.com/tutorials/blaze/running-on-mobile) when the application is coded.
- With ionic there are ways to [deploy the app as a website](http://stackoverflow.com/questions/33195748/deploy-ionic-as-a-website)
- ...

But these are all workarounds for a problem that is not really a problem: it is known that responsive layouts are failing (from [reports that date back to 2012](https://managewp.com/5-reasons-why-responsive-design-is-not-worth-it) to literature of today) to answer to users demands.
I think the biggest example of this has been [facebook's fail](https://www.infoq.com/news/2012/09/Facebook-HTML5-Native) where for several years you did not have a native app, but the only way to use fb was to navigate to the website from your device.

Another famous example was google's first implementation of [polymer](https://www.polymer-project.org/1.0/) which was too simplistic for desktop. Now it is much better though (psst: this might be another interesting framework for you to use :) )

So... what is the conclusion for all of this? Well, for me: I would develop and deploy with mobile in mind (if it becomes an app on the app store, it becomes an app on the app store.) and then develop a separate web-app for desktop **without** responsiveness in mind (makes things easier and it takes you 1/5th of the time since you already have all the code and just need to tweak UI).

And for the claim:

> And also, won't the choice of platform ultimately affect the other teams as well?    

I don't have a final, 100% always true answer to this, but in general (98% of cases): **no**. At the end of the day, you will develop using HTML and JS (no matter which framework) and the other groups are only producing some `div`s or very simple web-components that you can plug-in in different parts of your app.  
In the got.show example, the map is a reusable component (you see it in the /map, in the characters pages...). It's just a DOM element that you can define to take a certain size, and the behavior of the component is either defined internally or dependent on some initialization parameters which you can define at instantiation (so for example, the center of the map).

**Comment by MajorBreakfast** [comment]
Let's use cordova with polymer.

### Why cordova
- Cordova is simple and it works incredibly well
- There is no lock-in. Cordova-only code can be easily isolated with `if (typeof cordova !== 'undefined) { ... }` Cordova apps really are just regular websites

### Why polymer
- Light and flexible.
- Web components are awesome. Scoped styles and custom elements are the future
- Incredible UI, check out the elements catalog: https://elements.polymer-project.org/browse?package=paper-elements

I've experience with Cordova and Polymer, see https://www.wolfserviceapp.com. Cordova apps are in the play store/app store.

### Why not Meteor

I don't like how they mix server code with client code. I prefer a client that talks to the server over a cleanly designed JSON API provided by the server. I'd like to keep both code bases separate. Also, Meteor hides a lot of stuff due to the abstraction they provide.

### Why not Angular and Ember

Both frameworks have a lot of happy users. I've a lot of experience with ember. However I coded my latest project with polymer because compared to Polymer the two are much more heavy-weight and less flexible. The way the Polymer people solve everything with web components is really clever.

**Comment by WoH** [comment]
@MajorBreakfast I've started to work on an Ionic app for now, I agree on Cordova 100% and the conclusion to not use Meteor. I have never used Polymer and I know @johartl knows Angular1 so that sounded like a good compromise.
0970e8d78f1e2a760786a9bf045662bd100f6aff

**Comment by MajorBreakfast** [comment]
@WoH Did you look at my app created with polymer? (https://wolfserviceapp.com) The reason why I'm pushing Polymer is because of the UI. Polymer is crazy good at UI because google created all these web components.

Ionic on the other hand is just a css framework + angular + cordova. Correct me if I'm wrong. No modern web component features like shadow DOM and scoped styles.

**Comment by WoH** [comment]
I don't know polymer beyond "this thing exists".
Ionic 2 has everything you mentioned due to A2 but I didn't feel like I could push it due to the concerns @gyachdav mentioned [241184884](PokemonGoers/Catch-em-all/issues/3#issuecomment-241184884)

Edit: I'm checking polymer right now, give me a day or 2 and I will be ready to give useful feedback.

**Comment by MajorBreakfast** [comment]
I don't like the idea of using Angular 1 for the same reason as I don't like Python 2. ("Replaced by something newer")

About Angular 2: Are there any good UI solutions for it? UI is Polymer's strong point. So Angular 2 should be really good at UI as well if we were to choose it. As I see it, the UI is not a part of Angular's core. That in itself doesn't matter, as long there is a good solution.

@WoH Plz make sure to check out Polymer's animation capabilities. E.g. the grid demo at https://elements.polymer-project.org/elements/neon-animation?view=demo:demo/index.html&active=neon-animated-pages

**Comment by sacdallago** [comment]
@MajorBreakfast do you work for Google or something?
:joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy: 
JK, but yeah, I agree: Polymer is sick for mobile use.

**Comment by MajorBreakfast** [comment]
@sacdallago Haha Don't forget that I'm trashing Angular by Google :) But I agree. It's good for mobile. Mobile demands a lot of animations.

**Comment by MajorBreakfast** [comment]
Depending on what framework we choose, someone with expirience with the chosen framework should do the intial design of the app. We should determine what that exactly entails (routing + which pages) at our first team meeting. Once we have the coarse app structure, we can then divide the follow up work amongst ourselves.

**Comment by johartl** [comment]
> Depending on what framework we choose, someone with expirience with the chosen framework should do the intial design of the app.

Totally agree! If our choice happens to be Angular2 (or related) I'm glad to help out here. 
But regardless of which framework we will decide on I hope we make our choice as soon as possible (preferably tomorrow during our meeting) so we can finally start making progress (in terms of written code). It would be good if everyone in the group is aware of the frameworks and their advantages, drawbacks and in which set-up each of them works best. 
Looking forward to tomorrow's meeting :)

**Comment by MajorBreakfast** [comment]
Progress: In our team meeting yesterday we decided to use Angular 2. @WoH will do the initial implementation of the application. @johartl has also experience with Angular 2 and will support him.

Reasons for Angluar vs Polymer were:
- We have two team members with experience instead of one
- Angular 2 uses the new upcoming JavaScript module loader which is a better solution than HTML imports
- Angular 2 has features that are major selling points of Polymer as well
  - It uses shadow DOM
  - It has scoped styles
  - It has many preexisting UI components through Ionic

**Comment by johartl** [comment]
I updated the Travis build file on the ionic2 branch such that the builds are now passing again. Travis executes `npm test` in both the `ionic2` and `server` directory.
Do you think it would help to have a top-level `package.json` in the root folder? This file wouldn't have any dependencies but could define scripts for starting and testing the entire package. Also if we want to publish the package on npm wouldn't that require a top-level `package.json` as well?
On the contrary, having three different `package.json` seems a bit too much for this project :/ 
I'm not really sure about this so I would like to hear your opinion.

**Comment by johartl** [comment]
`gulp build` now produces a packaged app that will be copied directly to the `/server/app` directory from where it can be served by node.

**Comment by WoH** [comment]
#33
