### ISSUE TITLE
UI design drafts/mocks

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#5]
Discuss a possible user interface design and draw some mocks. 

From the project description:

> Here is a possible user story: when a user opens the website or the app the current location of the user will be shown. Additionally, the website/app will show automatically where the pokemons that are currently active are and where the pokemons that we predict to active in the nearest future (i.e. within half a day) will be located (all of this will be available from the app developed in project D). Hopefully, the website will be somewhat crowded by that data. Then, there needs to be a menu bar or something available (e.g. above the map or on the right side to it) that will list currently active or predicted pokemons. Clicking on one of them will make other pokemons on the map disappear, except of this clicked one.
> Separate web pages would allow the search and presentation of individual Pokemons and the information we gathered about them, including third party data (project A) and twitter analysis (project C)

**Comment by johartl** [comment]
To start the discussion, here are the mock ups from @WoH.
![Mock up mobile device](https://files.gitter.im/rostlabjs16projecte/Lobby/DAOA/Pok_mon-mobile.PNG)
![Mock up desktop browser](https://files.gitter.im/rostlabjs16projecte/Lobby/It5b/Pok_mon-Browser.PNG)

**Comment by goldbergtatyana** [comment]
Wow, very good job @WoH :+1: We also need to show what are the pokemons that we predict. This we can do either instead the place icons or in addition to them. 

Btw, looking at the updated description of project C (#PokemonGo) we will also show PokeMobs, i.e. if we see many tweets coming from a certain location we can expect many people being at that location who spotted someting interesting (= pokemon). The info about a mob is happening and where you will get from the group of Project C.

So, we will visualize 1) Pokemons and 2) Mobs. Both can ovelap (same time point, same location), but not necessarily (we can miss a prediction, but the mob we see on twitter).

@Woh what is your idea for the live feed? what does belong in there?

@all: My words are not final. Optimizations/suggestions are welcome! :)

**Comment by WoH** [comment]
@goldbergtatyana The image of the Pokémon should definitely displayed in the detail view, the X'd areas are the placeholders for the images.

I was thinking displaying the information in a feed that updates both on new feedback or new relevant predictions (in terms of time and loction), basically a text based index of the information otherwise presented on the map.

Edit 1:
![pokemon browser 2](https://cloud.githubusercontent.com/assets/2697771/17831483/1f392e5e-66ea-11e6-8b95-15a4fe8ce582.PNG)

This is supposed to a) give a clean overview and b) display relevant information instead of just having a bigger version of the mobile view.

It looks a bit messy because of all the boxes, but if the Pokémon details are displayed as cards I think it would look pretty fine.

Edit 2: [From Google's material card design guidelines](https://material-design.storage.googleapis.com/publish/material_v_9/0Bzhp5Z4wHba3NGo3QkpVWTNBZzA/components_cards_content3.png)

Edit 3: [Foundation offers these](http://zurb.com/building-blocks/material-card)

**Comment by goldbergtatyana** [comment]
I like @WoH! In the selected pokemon detail view we could show all kinds of detailed info. In the live feed  cards we can only show essential info for that pokemon.

How do we show PokeMobs?

**Comment by WoH** [comment]
@goldbergtatyana PokeMobs is the Pokemon database we use to get the Pokemon details?

First suggestion obviously to maybe add a search bar in the main screen that takes you to the "wiki view". Also, I should show the navigation menu already in the mockups, there should be a link to a "wiki view". I'm on it!

**Comment by WoH** [comment]
![pokemon browser 3](https://cloud.githubusercontent.com/assets/2697771/17831681/c22a19ca-66ef-11e6-9b72-68ff5a4c7aa6.PNG)

Working on a wiki overview now. Maybe show a search bar and a list of Pokémon or one of however many "Did you know?" tips if we can find a few before the user looks up a Pokémon.

**Comment by goldbergtatyana** [comment]
@WoH a PokeMob is a location with an accumulating number of tweets coming from. Inspired by [https://www.youtube.com/watch?v=MLdWbwQJWI0 ](https://www.youtube.com/watch?v=MLdWbwQJWI0) we can call such a location a mob. You will get the data about a mob from Group 5 ( #PokemonGo ).

**Comment by goldbergtatyana** [comment]
@WoH very much like your naviagtion menu. I can imagine having the following items there:
- Map 
- Pokemons (this is the wiki page; how about having it structured as [https://got.show/characters](https://got.show/characters)?)
- Statistics (or 'Did you know?') - im sure we'll be able to fetch a bunch of interesting facts from database and machine learning prediction people
- About

**Comment by WoH** [comment]
@goldbergtatyana Ok, thanks for clarifying. Since these mobs are around a certain Pokemon I think it  would it be nice to maybe have a card with red background and a special indicator on the map for these Mobs? 

I'm thinking of something like this:
![pokemon browser mob](https://cloud.githubusercontent.com/assets/2697771/17831815/0cc70480-66f4-11e6-8e48-114516239048.PNG)

**Comment by goldbergtatyana** [comment]
super cool, @WoH !!!

**Comment by sacdallago** [comment]
(One comment and one note)
Mockups look great and so are the ideas but keep in mind:
The target is a mobile app, not a desktop app! Always design thinking mobile first! ;) This changes a lot of things, most of the time (limited screen space, bandwidth, use pop-ups, models, etc)

**Comment by WoH** [comment]
@sacdallago I got that in mind, I am working on mobile view as we speak, but the main difference is the live feed that is probably not going to end up on the main screen for mobile in order to have more space for map and detail view on mobile.

**Comment by WoH** [comment]
![mobile reg](https://cloud.githubusercontent.com/assets/2697771/17832019/9765c716-66f9-11e6-8318-a32515189d78.PNG) ![mobile mob](https://cloud.githubusercontent.com/assets/2697771/17832020/9766dc78-66f9-11e6-99da-3542bbac4b40.PNG)

**Comment by WoH** [comment]
@sacdallago Thanks for the feedback, here are the mockups (regular Pokémon and Pokémon mob):
![mobile reg](https://cloud.githubusercontent.com/assets/2697771/17832019/9765c716-66f9-11e6-8318-a32515189d78.PNG) ![mobile mob](https://cloud.githubusercontent.com/assets/2697771/17832020/9766dc78-66f9-11e6-99da-3542bbac4b40.PNG)

**Comment by AlexanderLill** [comment]
@PokemonGoers/catch-em-all isn't this done already? :)

**Comment by sacdallago** [comment]
I suggest to open up new issues, should new UI discussions arise
