### ISSUE TITLE
Use cordova builds to serve Application

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#56]
Right now we directly push to server/app.
In the future, but especially in respect to android and iOS apps, we should default back to www/build and make use of cordova's platform specific builds (iOS, Android, Browser). This should also get rid of the cordova missing warning.

Change output folder to www/build (required so cordova detects builds) and run 
`cordova add platform browser` 
`cordova build browser`

or

`ionic platform add browser`
`ionic build browser`

Other platforms will probably have to be built manually for now:

iOS:

> Apple® tools required to build iOS applications only run on the OS X operating system on Intel-based Macs. Xcode® 6.0 (the minimum required version) runs only on OS X version 10.9 (Mavericks) or greater, and includes the iOS 8 SDK (Software Development Kit). To submit apps to the Apple App Store℠ requires the latest versions of the Apple tools.

Android:

> Cordova for Android requires the Android SDK which can be installed on OS X, Linux or Windows. See the Android SDK's System Requirements. Cordova's latest Android package supports up to Android API-Level 23. The supported Android API-Levels for the past few cordova-android releases can be found in this table:
> cordova-android Version     Supported Android API-Levels
> 5.X.X   14 - 23
> 4.1.X   14 - 22
> 4.0.X   10 - 22
> 3.7.X   10 - 21
> 
> Please note that the versions listed here are for Cordova's Android package, cordova-android, and not for the Cordova CLI. To determine what version of Cordova's Android package is installed in your Cordova project, run the command cordova platform ls in the directory that holds your project.
> 
> As a general rule, Android versions become unsupported by Cordova as they dip below 5% on Google's distribution dashboard.

**Comment by johartl** [comment]
What exactly is the issue with having a different output directory? Is there anything in particular you can't do?

What I like about the setup right now is that you just need to run `gulp build --release` and your server directory contains everything required to ship the app (whereas the ionic2 folder can be discarded). With the default Ionic setup you also have to prefix all files with `/build` which is just unnecessary.

```
@Page({
    templateUrl: '/build/pages/map/map.page.html'
})
```

The only exception of this rule is the `index.html` which then needs to be placed inside `/www` directly. I'd prefer to have this file in `/app` because that's where every other app-related files are too ;)

Of course all these reasons are just minor preferences of myself but so far I haven't seen a situation where the current setup didn't work.

**Comment by WoH** [comment]
you need /www/build structure for cordova to work which is necessary to build android or iOS apps. Also, if we use cordova to build for browser, we will get rid of the current warnings (cordova is missing).
I can explain the thought process tomorrow.
